import express from 'express';
import auth from './auth/router';
import users from './user/router';
import categories from './category/router';
import menus from './menu/router';
import subCategories from './subCategory/router';
import products from './product/router';
import productPrices from './productPrice/router';
import supplementCategories from './supplementCategory/router';
import supplements from './supplement/router';
import paymentMethods from './paymentMethod/router';
import addresses from './address/router';
import carts from './cart/router';
import orders from './order/router';
import notifications from './notification/router';
import deliveryPrices from './deliveryPrice/router';
import banners from './banner/router';
import discount from './discount/router';
import promoCodes from './promoCode/router';
import favourites from './favourite/router';
import ratings from './rating/router';
import stats from './stats/router';
import roles from './role/router';
import permissions from './permission/router';

const router = express.Router();

router.use('/auth', auth);
router.use('/users', users);
router.use('/categories', categories);
router.use('/menus', menus);
router.use('/sub-categories', subCategories);
router.use('/products', products);
router.use('/product-prices', productPrices);
router.use('/supplement-categories', supplementCategories);
router.use('/supplements', supplements);
router.use('/payment-methods', paymentMethods);
router.use('/addresses', addresses);
router.use('/carts', carts);
router.use('/orders', orders);
router.use('/notifications', notifications);
router.use('/delivery-prices', deliveryPrices);
router.use('/banners', banners);
router.use('/discount', discount);
router.use('/promo-codes', promoCodes);
router.use('/favourites', favourites);
router.use('/ratings', ratings);
router.use('/stats', stats);
router.use('/roles', roles);
router.use('/permissions', permissions);

export default router;
