import express from 'express';
import auth from './auth/router';
import users from './user/router';
import categories from './category/router';
import products from './product/router';
import paymentMethods from './paymentMethod/router';
import addresses from './address/router';
import carts from './cart/router';
import orders from './order/router';
import notifications from './notification/router';
import discount from './discount/router';
import promoCodes from './promoCode/router';
import favourites from './favourite/router';
import ratings from './rating/router';
import roles from './role/router';
import permissions from './permission/router';
import governorates from './governorate/router';
import areas from './area/router';
import stores from './store/router';
import deliveryPrices from './deliveryPrice/router';
import supplements from './supplement/router';

const router = express.Router();

router.use('/auth', auth);
router.use('/users', users);
router.use('/categories', categories);
router.use('/products', products);
router.use('/payment-methods', paymentMethods);
router.use('/addresses', addresses);
router.use('/carts', carts);
router.use('/orders', orders);
router.use('/notifications', notifications);
router.use('/discount', discount);
router.use('/promo-codes', promoCodes);
router.use('/favourites', favourites);
router.use('/ratings', ratings);
router.use('/roles', roles);
router.use('/permissions', permissions);
router.use('/governorates', governorates);
router.use('/areas', areas);
router.use('/stores', stores);
router.use('/delivery-prices', deliveryPrices);
router.use('/supplements', supplements);

export default router;
